from PyQt5 import QtCore, QtGui, QtWidgets


class DebugWindowUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(528, 632)
        Form.setStyleSheet("background-color: rgb(232, 232, 170);")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txt_debug = QtWidgets.QTextBrowser(Form)
        self.txt_debug.setGeometry(QtCore.QRect(30, 50, 381, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_debug.setFont(font)
        self.txt_debug.setStyleSheet("background-color: rgb(255, 255, 180);")
        self.txt_debug.setObjectName("txt_debug")
        self.txt_data = QtWidgets.QTextBrowser(Form)
        self.txt_data.setGeometry(QtCore.QRect(30, 360, 381, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_data.setFont(font)
        self.txt_data.setStyleSheet("background-color: rgb(255, 255, 180);")
        self.txt_data.setObjectName("txt_data")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 320, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_debug = QtWidgets.QPushButton(Form)
        self.btn_debug.setGeometry(QtCore.QRect(420, 60, 91, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_debug.setFont(font)
        self.btn_debug.setStyleSheet("background-color: rgb(220, 212, 147);")
        self.btn_debug.setObjectName("btn_debug")
        self.btn_data = QtWidgets.QPushButton(Form)
        self.btn_data.setGeometry(QtCore.QRect(420, 370, 91, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_data.setFont(font)
        self.btn_data.setStyleSheet("background-color: rgb(220, 212, 147);")
        self.btn_data.setObjectName("btn_data")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DebugForm"))
        self.label_2.setText(_translate("Form", "Debug:"))
        self.label_3.setText(_translate("Form", "Information about token and data packet:"))
        self.btn_debug.setText(_translate("Form", "Clear"))
        self.btn_data.setText(_translate("Form", "Clear"))